/**
 * @deevo/gcc-knowledge-graph — Scenario Registry
 *
 * 17 Strategic GCC Command Scenarios across 6 groups.
 * Canonical source — extracted from frontend/lib/gcc-graph.ts.
 *
 * Groups: Geopolitics (3) · Aviation (3) · Ports & Supply (3)
 *         Finance & Markets (3) · Utilities & State (3) · Sovereign (2)
 */

import { GCCScenario, ScenarioGroup, ScenarioGroupMeta } from './types';

// ═══════════════════════════════════════════════
// SCENARIO GROUP METADATA
// ═══════════════════════════════════════════════
export const SCENARIO_GROUPS: Record<ScenarioGroup, ScenarioGroupMeta> = {
  geopolitics:        { label: 'Geopolitics',                labelAr: 'الجيوسياسة',               icon: '🌍' },
  aviation:           { label: 'Aviation',                   labelAr: 'الطيران',                  icon: '✈️' },
  ports_supply:       { label: 'Ports & Supply Chains',      labelAr: 'الموانئ وسلاسل الإمداد',    icon: '🚢' },
  finance_markets:    { label: 'Finance & Markets',          labelAr: 'المالية والأسواق',          icon: '💰' },
  utilities_state:    { label: 'Utilities & State Capacity', labelAr: 'المرافق وقدرة الدولة',      icon: '⚡' },
  sovereign_projects: { label: 'Sovereign / Strategic',      labelAr: 'المشاريع السيادية',         icon: '🏗️' },
};

// ═══════════════════════════════════════════════
// ALL 17 SCENARIOS
// ═══════════════════════════════════════════════
export const gccScenarios: ReadonlyArray<GCCScenario> = Object.freeze([
  // ─── GROUP 1: GEOPOLITICS (3) ─────────────────
  {
    id: 'hormuz_closure', engineId: 'hormuz_closure',
    title: 'Strait of Hormuz Closure', titleAr: 'إغلاق مضيق هرمز',
    description: 'Full or partial closure of the Strait of Hormuz disrupting 21% of global oil transit, triggering multi-sector cascade across the GCC.',
    descriptionAr: 'إغلاق كلي أو جزئي لمضيق هرمز يعطّل 21% من عبور النفط العالمي، مما يُطلق تسلسل تأثيرات متعدد القطاعات عبر دول الخليج.',
    category: 'geopolitics', country: 'GCC', group: 'geopolitics',
    thesis: 'A Hormuz blockade does not just cut oil — it reprices every insurance contract, reroutes every ship, and grounds aviation within 72 hours.',
    thesisAr: 'إغلاق هرمز لا يقطع النفط فحسب — بل يعيد تسعير كل عقد تأمين، ويغير مسار كل سفينة، ويوقف الطيران خلال 72 ساعة.',
    sectors: ['oil', 'shipping', 'insurance', 'aviation', 'tourism', 'GDP'],
    keyEntities: ['geo_hormuz', 'eco_oil', 'eco_shipping', 'fin_insurers', 'eco_aviation', 'eco_tourism', 'eco_gdp'],
    mapModes: ['globe', 'shipping', 'heat', 'corridor'],
    formulaTags: ['F_flow', 'oil_export', 'shipping_cost', 'insurance_risk', 'aviation_cost', 'tourism_revenue', 'gdp_loss'],
    severityDefault: 0.90, timeHorizon: '72 hours – 30 days', timeHorizonAr: '72 ساعة – 30 يوم',
    expectedPropagationDomains: ['geography', 'infrastructure', 'economy', 'finance', 'society'],
    simulationType: 'deterministic', chokePoints: ['geo_hormuz'],
    geospatialAnchors: ['geo_hormuz', 'inf_jebel', 'inf_dammam', 'eco_oil'],
    shocks: [{ nodeId: 'geo_hormuz', impact: 0.90 }],
  },
  {
    id: 'us_iran_escalation', engineId: 'us_iran_escalation',
    title: 'Limited US\u2013Iran Escalation', titleAr: 'تصعيد أمريكي–إيراني محدود',
    description: 'A contained military exchange near the Strait triggers insurance repricing, capital flight, and aviation rerouting without full blockade.',
    descriptionAr: 'تبادل عسكري محدود بالقرب من المضيق يُطلق إعادة تسعير التأمين وهروب رؤوس الأموال وتغيير مسارات الطيران دون إغلاق كامل.',
    category: 'geopolitics', country: 'GCC', group: 'geopolitics',
    thesis: 'Even without blockade, proximity of conflict reprices GCC risk by 200\u2013400 bps and diverts 30% of shipping tonnage.',
    thesisAr: 'حتى بدون إغلاق، قرب الصراع يعيد تسعير مخاطر الخليج بـ 200-400 نقطة أساس ويحوّل 30% من حمولة الشحن.',
    sectors: ['insurance', 'shipping', 'aviation', 'finance', 'GDP'],
    keyEntities: ['geo_hormuz', 'fin_insurers', 'fin_reinsure', 'eco_shipping', 'eco_aviation', 'fin_tadawul'],
    mapModes: ['globe', 'shipping', 'flights', 'heat'],
    formulaTags: ['insurance_risk', 'shipping_cost', 'aviation_cost', 'capital_flight'],
    severityDefault: 0.65, timeHorizon: '48 hours – 14 days', timeHorizonAr: '48 ساعة – 14 يوم',
    expectedPropagationDomains: ['geography', 'economy', 'finance'],
    simulationType: 'probabilistic', chokePoints: ['geo_hormuz'],
    geospatialAnchors: ['geo_hormuz', 'fin_tadawul', 'eco_shipping'],
    shocks: [
      { nodeId: 'geo_hormuz', impact: 0.55 }, { nodeId: 'fin_insurers', impact: 0.70 },
      { nodeId: 'fin_reinsure', impact: 0.65 }, { nodeId: 'eco_shipping', impact: 0.40 },
    ],
  },
  {
    id: 'military_repositioning', engineId: 'military_repositioning',
    title: 'Military Repositioning in the Gulf', titleAr: 'إعادة تموضع عسكري في الخليج',
    description: 'Large-scale military movement near GCC waters triggers precautionary shipping rerouting, port delays, and airspace restrictions.',
    descriptionAr: 'تحركات عسكرية واسعة بالقرب من مياه الخليج تُطلق تحويل مسارات الشحن الاحترازية وتأخيرات الموانئ وتقييد المجال الجوي.',
    category: 'geopolitics', country: 'GCC', group: 'geopolitics',
    thesis: 'Military posturing without engagement still disrupts 15\u201320% of port throughput and triggers precautionary airspace closures.',
    thesisAr: 'الاستعراض العسكري بدون اشتباك يعطّل 15-20% من طاقة الموانئ ويُطلق إغلاقات جوية احترازية.',
    sectors: ['shipping', 'aviation', 'ports', 'insurance'],
    keyEntities: ['geo_hormuz', 'inf_jebel', 'inf_khalifa', 'eco_shipping', 'eco_aviation', 'inf_airport_throughput'],
    mapModes: ['globe', 'shipping', 'flights', 'corridor'],
    formulaTags: ['shipping_cost', 'port_throughput', 'aviation_cost', 'insurance_risk'],
    severityDefault: 0.50, timeHorizon: '1 – 21 days', timeHorizonAr: '1 – 21 يوم',
    expectedPropagationDomains: ['geography', 'infrastructure', 'economy'],
    simulationType: 'deterministic', chokePoints: ['geo_hormuz'],
    geospatialAnchors: ['geo_hormuz', 'inf_jebel', 'inf_khalifa', 'inf_dammam'],
    shocks: [
      { nodeId: 'geo_hormuz', impact: 0.40 }, { nodeId: 'eco_shipping', impact: 0.50 },
      { nodeId: 'inf_jebel', impact: 0.35 }, { nodeId: 'inf_airport_throughput', impact: -0.30 },
    ],
  },

  // ─── GROUP 2: AVIATION (3) ────────────────────
  {
    id: 'airspace_restriction', engineId: 'airspace_restriction',
    title: 'GCC Airspace Restriction', titleAr: 'تقييد المجال الجوي الخليجي',
    description: 'Partial GCC airspace closure forces rerouting of international flights, increasing fuel burn, ticket prices, and airline stress.',
    descriptionAr: 'إغلاق جزئي للمجال الجوي الخليجي يفرض تغيير مسارات الرحلات الدولية، مما يزيد استهلاك الوقود وأسعار التذاكر وضغط شركات الطيران.',
    category: 'economy', country: 'GCC', group: 'aviation',
    thesis: 'GCC airspace carries 40% of East-West air traffic. Restrictions cascade into global airline economics within 48 hours.',
    thesisAr: 'المجال الجوي الخليجي يحمل 40% من حركة الطيران بين الشرق والغرب. القيود تتسلسل إلى اقتصاديات الطيران العالمي خلال 48 ساعة.',
    sectors: ['aviation', 'tourism', 'airports', 'GDP'],
    keyEntities: ['eco_aviation', 'eco_saudia', 'eco_emirates', 'eco_qatar_aw', 'inf_airport_throughput', 'eco_tourism'],
    mapModes: ['flights', 'globe', 'heat'],
    formulaTags: ['aviation_cost', 'flight_cost', 'travel_demand', 'airport_throughput', 'aviation_stress'],
    severityDefault: 0.70, timeHorizon: '24 hours – 14 days', timeHorizonAr: '24 ساعة – 14 يوم',
    expectedPropagationDomains: ['infrastructure', 'economy', 'society'],
    simulationType: 'deterministic', chokePoints: [],
    geospatialAnchors: ['inf_dxb', 'inf_doh', 'inf_ruh', 'inf_auh'],
    shocks: [
      { nodeId: 'eco_aviation', impact: 0.75 }, { nodeId: 'inf_airport_throughput', impact: -0.60 },
      { nodeId: 'eco_saudia', impact: -0.50 }, { nodeId: 'eco_emirates', impact: -0.55 },
      { nodeId: 'eco_qatar_aw', impact: -0.50 },
    ],
  },
  {
    id: 'hajj_disruption', engineId: 'hajj_disruption',
    title: 'Hajj / Umrah Season Disruption', titleAr: 'تعطل موسم الحج والعمرة',
    description: 'Major disruption to Hajj season affecting 2M+ pilgrims, cascading through aviation, tourism revenue, JED airport operations, and Saudi GDP.',
    descriptionAr: 'تعطل كبير لموسم الحج يؤثر على أكثر من مليوني حاج، يتسلسل عبر الطيران وإيرادات السياحة وعمليات مطار جدة والناتج المحلي السعودي.',
    category: 'society', country: 'Saudi Arabia', group: 'aviation',
    thesis: 'Hajj is Saudi Arabia\'s second-largest revenue event. Disruption eliminates $12B+ in seasonal GDP and strands millions across 3 airports.',
    thesisAr: 'الحج ثاني أكبر حدث إيرادي للسعودية. التعطل يلغي أكثر من 12 مليار دولار من الناتج الموسمي ويُعلّق الملايين عبر 3 مطارات.',
    sectors: ['aviation', 'tourism', 'airports', 'society', 'GDP'],
    keyEntities: ['soc_hajj', 'inf_jed', 'eco_saudia', 'eco_tourism', 'soc_travel_d', 'eco_gdp'],
    mapModes: ['flights', 'globe', 'heat', 'corridor'],
    formulaTags: ['travel_demand', 'airport_throughput', 'tourism_revenue', 'gdp_loss'],
    severityDefault: 0.85, timeHorizon: '7 – 45 days', timeHorizonAr: '7 – 45 يوم',
    expectedPropagationDomains: ['infrastructure', 'economy', 'society'],
    simulationType: 'deterministic', chokePoints: [],
    geospatialAnchors: ['soc_hajj', 'inf_jed', 'inf_ruh', 'inf_dmm'],
    shocks: [
      { nodeId: 'soc_hajj', impact: 0.90 }, { nodeId: 'inf_jed', impact: 0.75 },
      { nodeId: 'soc_travel_d', impact: 0.65 },
    ],
  },
  {
    id: 'flight_rerouting', engineId: 'flight_rerouting',
    title: 'Flight Re-Routing under Regional Conflict', titleAr: 'تحويل مسارات الطيران تحت صراع إقليمي',
    description: 'Active conflict forces airlines to avoid GCC airspace, adding 2-4 hours to East-West routes and spiking fuel and ticket costs.',
    descriptionAr: 'صراع نشط يجبر شركات الطيران على تجنب المجال الجوي الخليجي، مما يضيف 2-4 ساعات للرحلات بين الشرق والغرب ويرفع تكاليف الوقود والتذاكر.',
    category: 'economy', country: 'GCC', group: 'aviation',
    thesis: 'Re-routing costs $8M/day per major airline. Six GCC carriers face simultaneous margin collapse while airports lose transit revenue.',
    thesisAr: 'تكلفة تغيير المسارات 8 ملايين دولار/يوم لكل شركة طيران كبرى. ست شركات خليجية تواجه انهيار هوامش متزامن بينما تفقد المطارات إيرادات العبور.',
    sectors: ['aviation', 'fuel', 'airports', 'tourism'],
    keyEntities: ['eco_aviation', 'eco_fuel', 'eco_emirates', 'eco_qatar_aw', 'eco_saudia', 'eco_av_stress'],
    mapModes: ['flights', 'globe', 'heat'],
    formulaTags: ['aviation_cost', 'flight_cost', 'aviation_stress', 'travel_demand'],
    severityDefault: 0.60, timeHorizon: '1 – 30 days', timeHorizonAr: '1 – 30 يوم',
    expectedPropagationDomains: ['economy', 'infrastructure', 'society'],
    simulationType: 'deterministic', chokePoints: [],
    geospatialAnchors: ['inf_dxb', 'inf_doh', 'inf_ruh', 'inf_auh', 'inf_bah', 'inf_mct'],
    shocks: [
      { nodeId: 'eco_aviation', impact: 0.65 }, { nodeId: 'eco_fuel', impact: 0.55 },
      { nodeId: 'eco_av_stress', impact: 0.70 }, { nodeId: 'inf_airport_throughput', impact: -0.40 },
    ],
  },

  // ─── GROUP 3: PORTS & SUPPLY CHAINS (3) ───────
  {
    id: 'jebel_ali_disruption', engineId: 'jebel_ali_disruption',
    title: 'Jebel Ali Port Disruption', titleAr: 'تعطل ميناء جبل علي',
    description: 'Major disruption at Jebel Ali Port affecting 30% of Middle East trade volume, cascading through logistics, insurance, and re-export economy.',
    descriptionAr: 'تعطل كبير في ميناء جبل علي يؤثر على 30% من حجم تجارة الشرق الأوسط، يتسلسل عبر الخدمات اللوجستية والتأمين واقتصاد إعادة التصدير.',
    category: 'economy', country: 'UAE', group: 'ports_supply',
    thesis: 'Jebel Ali handles 14.7M TEU/year. A 2-week shutdown cascades into $4.2B in trade delays and triggers regional port congestion.',
    thesisAr: 'ميناء جبل علي يتعامل مع 14.7 مليون حاوية/سنة. توقف أسبوعين يتسلسل إلى 4.2 مليار دولار تأخيرات تجارية ويُطلق ازدحام موانئ إقليمي.',
    sectors: ['shipping', 'logistics', 'insurance', 'trade', 'GDP'],
    keyEntities: ['inf_jebel', 'eco_shipping', 'eco_logistics', 'fin_insurers', 'eco_gdp'],
    mapModes: ['shipping', 'globe', 'heat', 'corridor'],
    formulaTags: ['port_throughput', 'shipping_cost', 'insurance_risk', 'gdp_loss'],
    severityDefault: 0.80, timeHorizon: '3 – 21 days', timeHorizonAr: '3 – 21 يوم',
    expectedPropagationDomains: ['infrastructure', 'economy', 'finance'],
    simulationType: 'deterministic', chokePoints: ['inf_jebel'],
    geospatialAnchors: ['inf_jebel', 'inf_khalifa', 'inf_hamad', 'eco_logistics'],
    shocks: [{ nodeId: 'inf_jebel', impact: 0.85 }, { nodeId: 'eco_shipping', impact: 0.70 }],
  },
  {
    id: 'gcc_port_congestion', engineId: 'gcc_port_congestion',
    title: 'GCC Port Congestion Crisis', titleAr: 'أزمة ازدحام الموانئ الخليجية',
    description: 'Simultaneous congestion across GCC ports due to rerouted global shipping, increasing dwell times, insurance costs, and food import delays.',
    descriptionAr: 'ازدحام متزامن عبر موانئ الخليج بسبب تحويل مسارات الشحن العالمي، مما يزيد أوقات الانتظار وتكاليف التأمين وتأخيرات استيراد الغذاء.',
    category: 'economy', country: 'GCC', group: 'ports_supply',
    thesis: 'GCC ports operate at 85% capacity. A 15% surge in rerouted vessels creates cascading delays that take 45+ days to clear.',
    thesisAr: 'موانئ الخليج تعمل بطاقة 85%. زيادة 15% في السفن المحوّلة تُنشئ تأخيرات متتالية تحتاج 45+ يوماً للتطهير.',
    sectors: ['shipping', 'ports', 'food', 'logistics', 'insurance'],
    keyEntities: ['inf_jebel', 'inf_dammam', 'inf_hamad', 'inf_khalifa', 'inf_shuwaikh', 'eco_shipping', 'eco_food'],
    mapModes: ['shipping', 'globe', 'heat'],
    formulaTags: ['port_throughput', 'shipping_cost', 'food_stress', 'insurance_risk'],
    severityDefault: 0.60, timeHorizon: '7 – 45 days', timeHorizonAr: '7 – 45 يوم',
    expectedPropagationDomains: ['infrastructure', 'economy', 'society'],
    simulationType: 'probabilistic', chokePoints: ['inf_jebel', 'inf_dammam'],
    geospatialAnchors: ['inf_jebel', 'inf_dammam', 'inf_hamad', 'inf_khalifa', 'inf_shuwaikh', 'inf_sohar'],
    shocks: [
      { nodeId: 'inf_jebel', impact: 0.55 }, { nodeId: 'inf_dammam', impact: 0.50 },
      { nodeId: 'inf_hamad', impact: 0.45 }, { nodeId: 'inf_khalifa', impact: 0.40 },
      { nodeId: 'inf_shuwaikh', impact: 0.40 }, { nodeId: 'eco_shipping', impact: 0.55 },
    ],
  },
  {
    id: 'food_security_shock', engineId: 'food_security_shock',
    title: 'Gulf Food Security Shock', titleAr: 'صدمة الأمن الغذائي الخليجي',
    description: 'Global grain supply disruption combined with Hormuz shipping bottleneck. GCC imports 85% of food — cascading through ports, cost of living, and social stability.',
    descriptionAr: 'تعطل إمدادات الحبوب العالمية مع اختناق شحن هرمز. دول الخليج تستورد 85% من الغذاء — يتسلسل عبر الموانئ وتكلفة المعيشة والاستقرار الاجتماعي.',
    category: 'economy', country: 'GCC', group: 'ports_supply',
    thesis: 'GCC imports 85% of calories. A 3-week shipping disruption creates 40-day food buffer depletion and triggers social instability signals.',
    thesisAr: 'دول الخليج تستورد 85% من السعرات الحرارية. تعطل شحن 3 أسابيع يستنفد المخزون الغذائي خلال 40 يوماً ويُطلق إشارات عدم استقرار اجتماعي.',
    sectors: ['food', 'shipping', 'society', 'ports', 'stability'],
    keyEntities: ['eco_food', 'soc_food_d', 'eco_shipping', 'geo_hormuz', 'soc_stability', 'soc_housing'],
    mapModes: ['shipping', 'globe', 'heat'],
    formulaTags: ['food_stress', 'shipping_cost', 'port_throughput'],
    severityDefault: 0.80, timeHorizon: '14 – 60 days', timeHorizonAr: '14 – 60 يوم',
    expectedPropagationDomains: ['geography', 'infrastructure', 'economy', 'society'],
    simulationType: 'hybrid', chokePoints: ['geo_hormuz'],
    geospatialAnchors: ['geo_hormuz', 'inf_jebel', 'inf_dammam', 'eco_food'],
    shocks: [
      { nodeId: 'eco_food', impact: 0.90 }, { nodeId: 'eco_shipping', impact: 0.60 },
      { nodeId: 'geo_hormuz', impact: 0.50 },
    ],
  },

  // ─── GROUP 4: FINANCE & MARKETS (3) ───────────
  {
    id: 'liquidity_stress', engineId: 'liquidity_stress',
    title: 'GCC Liquidity Stress', titleAr: 'ضغط السيولة الخليجي',
    description: 'Oil revenue collapse triggers sovereign deposit withdrawal, creating GCC-wide banking liquidity crunch affecting commercial lending and business credit.',
    descriptionAr: 'انهيار إيرادات النفط يُطلق سحب الودائع السيادية، مما يخلق أزمة سيولة مصرفية خليجية تؤثر على الإقراض التجاري والائتمان.',
    category: 'finance', country: 'GCC', group: 'finance_markets',
    thesis: 'GCC banks hold 60% sovereign deposits. A coordinated withdrawal triggers a liquidity spiral that freezes commercial lending within 5 days.',
    thesisAr: 'البنوك الخليجية تحتفظ بـ 60% ودائع سيادية. سحب منسق يُطلق دوامة سيولة تجمّد الإقراض التجاري خلال 5 أيام.',
    sectors: ['banking', 'finance', 'oil', 'business', 'employment'],
    keyEntities: ['fin_banking', 'fin_sama', 'fin_uae_cb', 'fin_kw_cb', 'eco_oil', 'soc_business'],
    mapModes: ['globe', 'heat'],
    formulaTags: ['banking_stress', 'gdp_loss'],
    severityDefault: 0.75, timeHorizon: '3 – 30 days', timeHorizonAr: '3 – 30 يوم',
    expectedPropagationDomains: ['finance', 'economy', 'society'],
    simulationType: 'deterministic', chokePoints: [],
    geospatialAnchors: ['fin_sama', 'fin_uae_cb', 'fin_tadawul'],
    shocks: [
      { nodeId: 'fin_banking', impact: 0.85 }, { nodeId: 'fin_sama', impact: 0.60 },
      { nodeId: 'eco_oil', impact: 0.70 },
    ],
  },
  {
    id: 'fx_gold_crypto_shock', engineId: 'fx_gold_crypto_shock',
    title: 'FX / Gold / Crypto Market Shock', titleAr: 'صدمة أسواق العملات والذهب والعملات الرقمية',
    description: 'Simultaneous dollar strengthening, gold spike, and crypto volatility create cross-asset stress on GCC financial markets and central bank reserves.',
    descriptionAr: 'تعزيز الدولار وارتفاع الذهب وتقلبات العملات الرقمية المتزامنة تخلق ضغطاً عبر الأصول على الأسواق المالية الخليجية واحتياطيات البنوك المركزية.',
    category: 'finance', country: 'GCC', group: 'finance_markets',
    thesis: 'GCC currencies are dollar-pegged. A rapid dollar move forces central banks to defend pegs while managing $180B in sovereign wealth rebalancing.',
    thesisAr: 'العملات الخليجية مربوطة بالدولار. تحرك سريع للدولار يجبر البنوك المركزية على الدفاع عن الربط مع إدارة 180 مليار دولار إعادة توازن ثروات سيادية.',
    sectors: ['finance', 'banking', 'markets', 'sovereign'],
    keyEntities: ['fin_sama', 'fin_uae_cb', 'fin_kw_cb', 'fin_qa_cb', 'fin_tadawul', 'fin_banking'],
    mapModes: ['globe', 'heat'],
    formulaTags: ['banking_stress', 'gdp_loss'],
    severityDefault: 0.60, timeHorizon: '1 – 14 days', timeHorizonAr: '1 – 14 يوم',
    expectedPropagationDomains: ['finance', 'economy'],
    simulationType: 'probabilistic', chokePoints: [],
    geospatialAnchors: ['fin_sama', 'fin_uae_cb', 'fin_kw_cb', 'fin_qa_cb', 'fin_tadawul'],
    shocks: [
      { nodeId: 'fin_sama', impact: 0.55 }, { nodeId: 'fin_uae_cb', impact: 0.50 },
      { nodeId: 'fin_kw_cb', impact: 0.45 }, { nodeId: 'fin_qa_cb', impact: 0.45 },
      { nodeId: 'fin_tadawul', impact: 0.65 },
    ],
  },
  {
    id: 'insurance_repricing', engineId: 'insurance_repricing',
    title: 'Insurance & Reinsurance Risk Repricing', titleAr: 'إعادة تسعير مخاطر التأمين وإعادة التأمين',
    description: 'Reinsurance withdrawal from GCC markets following catastrophic loss event, raising premiums across shipping, aviation, and infrastructure sectors.',
    descriptionAr: 'انسحاب إعادة التأمين من أسواق الخليج بعد حدث خسارة كارثية، مما يرفع أقساط التأمين عبر قطاعات الشحن والطيران والبنية التحتية.',
    category: 'finance', country: 'GCC', group: 'finance_markets',
    thesis: 'Reinsurers pulling $15B in GCC capacity forces self-insurance, raising operational costs by 30-50% across all logistics sectors.',
    thesisAr: 'سحب شركات إعادة التأمين 15 مليار دولار من طاقة الخليج يفرض التأمين الذاتي، مما يرفع التكاليف التشغيلية 30-50% عبر جميع قطاعات الخدمات اللوجستية.',
    sectors: ['insurance', 'shipping', 'aviation', 'infrastructure'],
    keyEntities: ['fin_reinsure', 'fin_ins_risk', 'fin_insurers', 'eco_shipping', 'eco_aviation'],
    mapModes: ['globe', 'heat', 'shipping', 'flights'],
    formulaTags: ['insurance_risk', 'shipping_cost', 'aviation_cost'],
    severityDefault: 0.75, timeHorizon: '7 – 90 days', timeHorizonAr: '7 – 90 يوم',
    expectedPropagationDomains: ['finance', 'economy', 'infrastructure'],
    simulationType: 'deterministic', chokePoints: [],
    geospatialAnchors: ['fin_insurers', 'fin_reinsure', 'eco_shipping'],
    shocks: [{ nodeId: 'fin_reinsure', impact: 0.85 }, { nodeId: 'fin_ins_risk', impact: 0.75 }],
  },

  // ─── GROUP 5: UTILITIES & STATE CAPACITY (3) ──
  {
    id: 'gcc_grid_failure', engineId: 'gcc_grid_failure',
    title: 'GCC Power Grid Failure', titleAr: 'انهيار شبكة الكهرباء الخليجية',
    description: 'Peak summer power grid failure cascading through desalination, telecom infrastructure, business operations, and citizen welfare.',
    descriptionAr: 'انهيار شبكة الكهرباء في ذروة الصيف يتسلسل عبر التحلية والبنية التحتية للاتصالات والعمليات التجارية ورفاهية المواطنين.',
    category: 'infrastructure', country: 'GCC', group: 'utilities_state',
    thesis: 'GCC power grids run at 95% capacity in summer. A 10% drop cascades into desalination failure within 6 hours, creating a water crisis.',
    thesisAr: 'شبكات الكهرباء الخليجية تعمل بطاقة 95% في الصيف. انخفاض 10% يتسلسل إلى فشل التحلية خلال 6 ساعات، مما يخلق أزمة مياه.',
    sectors: ['power', 'water', 'telecom', 'society', 'business'],
    keyEntities: ['inf_power', 'inf_desal', 'inf_telecom', 'soc_citizens', 'soc_business'],
    mapModes: ['globe', 'heat'],
    formulaTags: ['utility_availability', 'gdp_loss'],
    severityDefault: 0.85, timeHorizon: '6 hours – 7 days', timeHorizonAr: '6 ساعات – 7 أيام',
    expectedPropagationDomains: ['infrastructure', 'society', 'economy'],
    simulationType: 'deterministic', chokePoints: [],
    geospatialAnchors: ['inf_power', 'inf_desal', 'inf_telecom'],
    shocks: [
      { nodeId: 'inf_power', impact: 0.90 }, { nodeId: 'inf_desal', impact: 0.80 },
      { nodeId: 'inf_telecom', impact: 0.70 },
    ],
  },
  {
    id: 'water_electricity_disruption', engineId: 'water_electricity_disruption',
    title: 'Electricity & Water Disruption', titleAr: 'تعطل الكهرباء والمياه',
    description: 'Coordinated infrastructure failure affecting power generation and desalination plants, threatening public health and economic activity.',
    descriptionAr: 'فشل بنية تحتية منسق يؤثر على توليد الطاقة ومحطات التحلية، مما يهدد الصحة العامة والنشاط الاقتصادي.',
    category: 'infrastructure', country: 'GCC', group: 'utilities_state',
    thesis: 'GCC produces 99% of drinking water from desalination. Power failure means water failure means public health emergency within 48 hours.',
    thesisAr: 'دول الخليج تنتج 99% من مياه الشرب من التحلية. انقطاع الكهرباء يعني انقطاع المياه يعني طوارئ صحية عامة خلال 48 ساعة.',
    sectors: ['power', 'water', 'health', 'society', 'stability'],
    keyEntities: ['inf_power', 'inf_desal', 'gov_water', 'soc_citizens', 'soc_stability'],
    mapModes: ['globe', 'heat'],
    formulaTags: ['utility_availability', 'gdp_loss'],
    severityDefault: 0.80, timeHorizon: '12 hours – 14 days', timeHorizonAr: '12 ساعة – 14 يوم',
    expectedPropagationDomains: ['infrastructure', 'society'],
    simulationType: 'deterministic', chokePoints: [],
    geospatialAnchors: ['inf_power', 'inf_desal', 'gov_water'],
    shocks: [
      { nodeId: 'inf_power', impact: 0.85 }, { nodeId: 'inf_desal', impact: 0.85 },
      { nodeId: 'gov_water', impact: 0.70 },
    ],
  },
  {
    id: 'summer_utility_stress', engineId: 'summer_utility_stress',
    title: 'Summer Utility Stress under Conflict', titleAr: 'ضغط المرافق الصيفي تحت الصراع',
    description: 'Peak summer demand combined with regional conflict disrupts fuel supply for power generation, creating cascading utility and social stress.',
    descriptionAr: 'ذروة الطلب الصيفي مع صراع إقليمي تعطّل إمدادات الوقود لتوليد الطاقة، مما يخلق ضغطاً متتالياً على المرافق والمجتمع.',
    category: 'infrastructure', country: 'GCC', group: 'utilities_state',
    thesis: 'Summer + conflict = double stress on utilities. Fuel supply disruption during peak cooling demand creates cascading failures across the power-water-telecom nexus.',
    thesisAr: 'الصيف + الصراع = ضغط مزدوج على المرافق. تعطل إمدادات الوقود أثناء ذروة طلب التبريد يخلق فشلاً متتالياً عبر ترابط الكهرباء-المياه-الاتصالات.',
    sectors: ['power', 'water', 'fuel', 'telecom', 'society'],
    keyEntities: ['inf_power', 'inf_desal', 'eco_fuel', 'inf_telecom', 'soc_citizens', 'soc_stability', 'geo_hormuz'],
    mapModes: ['globe', 'heat', 'shipping'],
    formulaTags: ['utility_availability', 'shipping_cost', 'gdp_loss'],
    severityDefault: 0.75, timeHorizon: '3 – 30 days', timeHorizonAr: '3 – 30 يوم',
    expectedPropagationDomains: ['geography', 'infrastructure', 'economy', 'society'],
    simulationType: 'hybrid', chokePoints: ['geo_hormuz'],
    geospatialAnchors: ['inf_power', 'inf_desal', 'eco_fuel', 'geo_hormuz'],
    shocks: [
      { nodeId: 'inf_power', impact: 0.75 }, { nodeId: 'inf_desal', impact: 0.65 },
      { nodeId: 'eco_fuel', impact: 0.70 }, { nodeId: 'geo_hormuz', impact: 0.45 },
    ],
  },

  // ─── GROUP 6: SOVEREIGN / STRATEGIC (2) ───────
  {
    id: 'vision2030_stress', engineId: 'vision2030_stress',
    title: 'Vision 2030 Stress under Regional Shock', titleAr: 'ضغط رؤية 2030 تحت صدمة إقليمية',
    description: 'Regional instability threatens Vision 2030 investment timeline, affecting tourism corridors, mega projects, FDI flows, and employment targets.',
    descriptionAr: 'عدم الاستقرار الإقليمي يهدد الجدول الزمني لاستثمارات رؤية 2030، مما يؤثر على ممرات السياحة والمشاريع الكبرى وتدفقات الاستثمار الأجنبي وأهداف التوظيف.',
    category: 'economy', country: 'Saudi Arabia', group: 'sovereign_projects',
    thesis: 'Vision 2030 depends on $1.3T in committed investment. Regional conflict delays 20-30% of project timelines and diverts sovereign capital to defense.',
    thesisAr: 'رؤية 2030 تعتمد على 1.3 تريليون دولار استثمارات ملتزمة. الصراع الإقليمي يؤخر 20-30% من الجداول الزمنية للمشاريع ويحوّل رأس المال السيادي للدفاع.',
    sectors: ['tourism', 'GDP', 'employment', 'aviation', 'finance'],
    keyEntities: ['eco_tourism', 'eco_gdp', 'soc_employment', 'gov_tourism', 'fin_sama', 'eco_saudia'],
    mapModes: ['globe', 'heat'],
    formulaTags: ['tourism_revenue', 'gdp_loss', 'aviation_stress'],
    severityDefault: 0.65, timeHorizon: '30 – 365 days', timeHorizonAr: '30 – 365 يوم',
    expectedPropagationDomains: ['economy', 'finance', 'society'],
    simulationType: 'probabilistic', chokePoints: [],
    geospatialAnchors: ['eco_tourism', 'eco_gdp', 'fin_sama', 'gov_tourism'],
    shocks: [
      { nodeId: 'eco_tourism', impact: -0.65 }, { nodeId: 'soc_employment', impact: -0.50 },
      { nodeId: 'fin_sama', impact: 0.40 }, { nodeId: 'eco_gdp', impact: -0.55 },
    ],
  },
  {
    id: 'mega_projects_pressure', engineId: 'mega_projects_pressure',
    title: 'Mega Projects & Tourism Corridor Pressure', titleAr: 'ضغط المشاريع الكبرى وممرات السياحة',
    description: 'Construction delays, labor shortages, and financing stress on GCC mega projects create ripple effects through employment, housing, and economic growth.',
    descriptionAr: 'تأخيرات البناء ونقص العمالة وضغط التمويل على المشاريع الكبرى الخليجية تخلق تأثيرات متموجة عبر التوظيف والإسكان والنمو الاقتصادي.',
    category: 'economy', country: 'GCC', group: 'sovereign_projects',
    thesis: 'GCC mega projects employ 3M+ workers. Construction delays cascade into housing oversupply, labor unrest, and banking exposure to project finance.',
    thesisAr: 'المشاريع الكبرى الخليجية توظف أكثر من 3 ملايين عامل. تأخيرات البناء تتسلسل إلى فائض إسكان واضطرابات عمالية وتعرض بنكي لتمويل المشاريع.',
    sectors: ['employment', 'housing', 'tourism', 'banking', 'GDP'],
    keyEntities: ['soc_employment', 'soc_housing', 'soc_expats', 'eco_tourism', 'fin_banking', 'eco_gdp'],
    mapModes: ['globe', 'heat'],
    formulaTags: ['banking_stress', 'gdp_loss', 'tourism_revenue'],
    severityDefault: 0.55, timeHorizon: '90 – 365 days', timeHorizonAr: '90 – 365 يوم',
    expectedPropagationDomains: ['economy', 'finance', 'society'],
    simulationType: 'probabilistic', chokePoints: [],
    geospatialAnchors: ['eco_tourism', 'soc_employment', 'soc_housing', 'fin_banking'],
    shocks: [
      { nodeId: 'soc_employment', impact: -0.55 }, { nodeId: 'soc_housing', impact: 0.50 },
      { nodeId: 'soc_expats', impact: -0.45 }, { nodeId: 'fin_banking', impact: 0.40 },
      { nodeId: 'eco_tourism', impact: -0.45 },
    ],
  },
]);

/** Lookup scenario by ID */
export function getScenario(id: string): GCCScenario | undefined {
  return gccScenarios.find(s => s.id === id);
}

/** Get scenarios by group */
export function getScenariosByGroup(group: ScenarioGroup): GCCScenario[] {
  return gccScenarios.filter(s => s.group === group);
}
