"""Seed data for actors (organizations, governments, militias) in GCC region."""

from datetime import datetime, timezone
from app.schema import Actor, ActorType


def get_seed_actors() -> list[Actor]:
    """Generate seed actors for GCC region.
    
    Returns a list of 15 major regional actors including government entities,
    military organizations, militant groups, and regional organizations
    active in 2023-2026 timeframe.
    
    Returns:
        list[Actor]: List of Actor instances with names, types, affiliations,
                    and descriptions in English and Arabic.
    """
    now = datetime.now(timezone.utc)
    
    actors = [
        # Government Entities
        Actor(
            id="actor_001",
            name="Saudi Ministry of Defense",
            name_ar="وزارة الدفاع السعودية",
            actor_type=ActorType.GOVERNMENT,
            country_code="SAU",
            region="GCC",
            description="Saudi Arabia's primary military and defense authority, responsible for armed forces operations",
            description_ar="السلطة العسكرية الرئيسية في المملكة العربية السعودية المسؤولة عن العمليات العسكرية",
            is_state_actor=True,
            associated_aliases=["Saudi Ministry of Defence", "MoD Saudi Arabia"],
            relationship_to_gcc=True,
            confidence=0.99,
            source_type="government_api",
            last_updated=now,
        ),
        Actor(
            id="actor_002",
            name="UAE General Command of Armed Forces",
            name_ar="القيادة العامة لقوات الإمارات المسلحة",
            actor_type=ActorType.GOVERNMENT,
            country_code="ARE",
            region="GCC",
            description="United Arab Emirates armed forces command, overseeing military operations and defense",
            description_ar="قيادة القوات المسلحة الإماراتية المسؤولة عن العمليات العسكرية والدفاع",
            is_state_actor=True,
            associated_aliases=["UAE Armed Forces", "UAECAF"],
            relationship_to_gcc=True,
            confidence=0.99,
            source_type="government_api",
            last_updated=now,
        ),
        Actor(
            id="actor_003",
            name="Qatar Ministry of Defense",
            name_ar="وزارة الدفاع القطرية",
            actor_type=ActorType.GOVERNMENT,
            country_code="QAT",
            region="GCC",
            description="Qatar's defense ministry managing military forces and security",
            description_ar="وزارة الدفاع القطرية المسؤولة عن إدارة القوات العسكرية والأمن",
            is_state_actor=True,
            associated_aliases=["Qatar Ministry of Defence"],
            relationship_to_gcc=True,
            confidence=0.99,
            source_type="government_api",
            last_updated=now,
        ),
        Actor(
            id="actor_004",
            name="Omani Royal Navy",
            name_ar="البحرية الملكية العمانية",
            actor_type=ActorType.GOVERNMENT,
            country_code="OMN",
            region="Indian Ocean",
            description="Oman's naval force responsible for maritime security and Gulf operations",
            description_ar="القوة البحرية العمانية المسؤولة عن الأمن البحري والعمليات في الخليج",
            is_state_actor=True,
            associated_aliases=["Royal Oman Navy", "Sultanate Navy"],
            relationship_to_gcc=True,
            confidence=0.98,
            source_type="government_api",
            last_updated=now,
        ),
        Actor(
            id="actor_005",
            name="Kuwait General Command of Armed Forces",
            name_ar="القيادة العامة لقوات الجيش الكويتي",
            actor_type=ActorType.GOVERNMENT,
            country_code="KWT",
            region="GCC",
            description="Kuwait's primary military authority overseeing all armed services",
            description_ar="السلطة العسكرية الكويتية الرئيسية المسؤولة عن جميع الخدمات المسلحة",
            is_state_actor=True,
            associated_aliases=["Kuwait Armed Forces", "KCAF"],
            relationship_to_gcc=True,
            confidence=0.98,
            source_type="government_api",
            last_updated=now,
        ),
        Actor(
            id="actor_006",
            name="Bahrain Ministry of Defense",
            name_ar="وزارة الدفاع البحرينية",
            actor_type=ActorType.GOVERNMENT,
            country_code="BHR",
            region="GCC",
            description="Bahrain's defense ministry managing military operations",
            description_ar="وزارة الدفاع البحرينية المسؤولة عن العمليات العسكرية",
            is_state_actor=True,
            associated_aliases=["Bahrain Ministry of Defence"],
            relationship_to_gcc=True,
            confidence=0.98,
            source_type="government_api",
            last_updated=now,
        ),
        
        # Regional Organizations
        Actor(
            id="actor_007",
            name="United Nations Mission in GCC",
            name_ar="بعثة الأمم المتحدة في الخليج",
            actor_type=ActorType.ORGANIZATION,
            country_code="INT",
            region="GCC",
            description="International organization focused on peacekeeping and regional stability",
            description_ar="منظمة دولية تركز على حفظ السلام والاستقرار الإقليمي",
            is_state_actor=False,
            associated_aliases=["UNOGC", "UN in GCC"],
            relationship_to_gcc=True,
            confidence=0.85,
            source_type="internal_system",
            last_updated=now,
        ),
        Actor(
            id="actor_008",
            name="Gulf Cooperation Council Secretariat",
            name_ar="أمانة مجلس التعاون الخليجي",
            actor_type=ActorType.ORGANIZATION,
            country_code="INT",
            region="GCC",
            description="Multilateral GCC organization coordinating member states policies",
            description_ar="منظمة متعددة الأطراف تنسق سياسات دول مجلس التعاون",
            is_state_actor=False,
            associated_aliases=["GCC Secretariat", "GCCS"],
            relationship_to_gcc=True,
            confidence=0.96,
            source_type="internal_system",
            last_updated=now,
        ),
        
        # Militant/Non-State Actors
        Actor(
            id="actor_009",
            name="Houthi Movement (Ansar Allah)",
            name_ar="حركة الحوثيين (أنصار الله)",
            actor_type=ActorType.MILITIA,
            country_code="YEM",
            region="Red Sea",
            description="Yemen-based militant organization conducting maritime attacks in Red Sea and Gulf of Aden",
            description_ar="منظمة عسكرية يمنية تشن هجمات بحرية في البحر الأحمر وخليج عدن",
            is_state_actor=False,
            associated_aliases=["Houthi", "Ansar Allah", "Houthis"],
            relationship_to_gcc=False,
            confidence=0.92,
            source_type="human_report",
            last_updated=now,
        ),
        Actor(
            id="actor_010",
            name="Iranian Revolutionary Guard Corps (IRGC)",
            name_ar="الحرس الثوري الإسلامي",
            actor_type=ActorType.GOVERNMENT,
            country_code="IRN",
            region="Persian Gulf",
            description="Iran's elite military organization conducting operations in Persian Gulf",
            description_ar="القوة العسكرية الإيرانية النخبة التي تجري عمليات في الخليج الفارسي",
            is_state_actor=True,
            associated_aliases=["IRGC", "Islamic Revolutionary Guard", "Sepah"],
            relationship_to_gcc=False,
            confidence=0.94,
            source_type="human_report",
            last_updated=now,
        ),
        Actor(
            id="actor_011",
            name="Popular Mobilization Forces (Iraq)",
            name_ar="قوات الحشد الشعبي (العراق)",
            actor_type=ActorType.MILITIA,
            country_code="IRQ",
            region="Iraq",
            description="Iraqi paramilitary organization conducting operations against regional actors",
            description_ar="منظمة عراقية بارامسكرية تجري عمليات ضد الجهات الإقليمية",
            is_state_actor=False,
            associated_aliases=["PMF", "PMU", "Hashed al-Shaabi"],
            relationship_to_gcc=False,
            confidence=0.87,
            source_type="human_report",
            last_updated=now,
        ),
        
        # Commercial Entities
        Actor(
            id="actor_012",
            name="Saudi Aramco",
            name_ar="أرامكو السعودية",
            actor_type=ActorType.ORGANIZATION,
            country_code="SAU",
            region="GCC",
            description="Major Saudi oil and gas company critical to regional energy infrastructure",
            description_ar="شركة نفط وغاز سعودية رئيسية حيوية لل infrastructure الطاقة الإقليمية",
            is_state_actor=False,
            associated_aliases=["Saudi Petroleum", "Saudi Oil Company"],
            relationship_to_gcc=True,
            confidence=0.99,
            source_type="commercial_api",
            last_updated=now,
        ),
        Actor(
            id="actor_013",
            name="DP World",
            name_ar="موانئ دبي العالمية",
            actor_type=ActorType.ORGANIZATION,
            country_code="ARE",
            region="GCC",
            description="Major UAE-based port operator managing regional maritime infrastructure",
            description_ar="مشغل موانئ إماراتي رئيسي يدير infrastructure الموانئ الإقليمية",
            is_state_actor=False,
            associated_aliases=["Dubai Ports", "DP World Terminals"],
            relationship_to_gcc=True,
            confidence=0.97,
            source_type="commercial_api",
            last_updated=now,
        ),
        Actor(
            id="actor_014",
            name="Qatar Energy",
            name_ar="قطر للطاقة",
            actor_type=ActorType.ORGANIZATION,
            country_code="QAT",
            region="GCC",
            description="Qatar's major energy corporation controlling LNG and oil exports",
            description_ar="شركة الطاقة القطرية الرئيسية التي تتحكم في صادرات الغاز الطبيعي المسال والنفط",
            is_state_actor=False,
            associated_aliases=["Qatar Petroleum", "QatarEnergy"],
            relationship_to_gcc=True,
            confidence=0.98,
            source_type="commercial_api",
            last_updated=now,
        ),
        
        # International Organizations
        Actor(
            id="actor_015",
            name="International Maritime Organization",
            name_ar="منظمة البحرية الدولية",
            actor_type=ActorType.ORGANIZATION,
            country_code="INT",
            region="Global",
            description="UN agency setting maritime safety and security standards",
            description_ar="وكالة الأمم المتحدة التي تضع معايير السلامة والأمن البحري",
            is_state_actor=False,
            associated_aliases=["IMO", "International Maritime Org"],
            relationship_to_gcc=True,
            confidence=0.95,
            source_type="internal_system",
            last_updated=now,
        ),
    ]
    
    return actors
