"""Seed data for GCC airports.

This module provides realistic airport data for the GCC region (2023-2026).
All airports use real ICAO/IATA codes and coordinates.
"""

from datetime import datetime, timedelta
from typing import Optional

from app.schema import City, GeoPoint, Airport, AssetType, SourceType


def get_seed_airports() -> list[Airport]:
    """Return a list of GCC region airports with realistic data.
    
    Includes major commercial, regional, and military airports across:
    - Saudi Arabia (Riyadh, Jeddah, Dammam, etc.)
    - UAE (Dubai, Abu Dhabi, Sharjah, etc.)
    - Qatar (Doha, etc.)
    - Kuwait (Kuwait City, etc.)
    - Bahrain (Manama, etc.)
    - Oman (Muscat, etc.)
    - Yemen (Sana'a, Aden)
    - Iraq (Baghdad, Basra)
    
    Returns:
        list[Airport]: 30 realistic GCC airports
    """
    airports = []
    
    # Saudi Arabia - Major Airports
    airports.append(Airport(
        id="apt-001",
        name="King Abdulaziz International Airport",
        name_ar="مطار الملك عبدالعزيز الدولي",
        icao_code="OERK",
        iata_code="RUH",
        location=GeoPoint(latitude=24.9266, longitude=46.6989),
        country_code="SAU",
        operational_status="operational",
        capacity="36 million passengers annually",
        critical_infrastructure=True,
        runways=3,
        elevation_meters=615,
        max_capacity_daily=1200,
        airlines=["Saudia", "Flyadeal", "flynas", "international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-002",
        name="King Abdulaziz International Airport Jeddah",
        name_ar="مطار الملك عبدالعزيز الدولي - جدة",
        icao_code="OEJN",
        iata_code="JED",
        location=GeoPoint(latitude=21.5433, longitude=39.1727),
        country_code="SAU",
        operational_status="operational",
        capacity="24 million passengers annually",
        critical_infrastructure=True,
        runways=3,
        elevation_meters=15,
        max_capacity_daily=800,
        airlines=["Saudia", "Flyadeal", "international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-003",
        name="King Fahd International Airport",
        name_ar="مطار الملك فهد الدولي",
        icao_code="OEDF",
        iata_code="DMM",
        location=GeoPoint(latitude=26.1810, longitude=50.1992),
        country_code="SAU",
        operational_status="operational",
        capacity="12 million passengers annually",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=7,
        max_capacity_daily=400,
        airlines=["Saudia", "Flyadeal", "regional carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-004",
        name="Prince Sultan bin Abdulaziz Airport",
        name_ar="مطار الأمير سلطان بن عبدالعزيز",
        icao_code="OEMA",
        iata_code="ABT",
        location=GeoPoint(latitude=26.2025, longitude=49.9775),
        country_code="SAU",
        operational_status="operational",
        capacity="Military with civilian use",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=16,
        max_capacity_daily=200,
        airlines=["Saudia", "regional operators"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.95,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-005",
        name="Prince Abdulaziz bin Musaed Air Base",
        name_ar="قاعدة الأمير عبدالعزيز بن مساعد الجوية",
        icao_code="OEYN",
        iata_code="YNB",
        location=GeoPoint(latitude=24.7052, longitude=46.7203),
        country_code="SAU",
        operational_status="operational",
        capacity="Military - limited civilian",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=644,
        max_capacity_daily=100,
        airlines=["Royal Saudi Air Force"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.90,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    # UAE - Major Airports
    airports.append(Airport(
        id="apt-006",
        name="Dubai International Airport",
        name_ar="مطار دبي الدولي",
        icao_code="OMDB",
        iata_code="DXB",
        location=GeoPoint(latitude=25.2528, longitude=55.3644),
        country_code="ARE",
        operational_status="operational",
        capacity="88.2 million passengers annually",
        critical_infrastructure=True,
        runways=3,
        elevation_meters=5,
        max_capacity_daily=2900,
        airlines=["Emirates", "FlyDubai", "200+ international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-007",
        name="Abu Dhabi International Airport",
        name_ar="مطار أبو ظبي الدولي",
        icao_code="OMAD",
        iata_code="AUH",
        location=GeoPoint(latitude=24.4539, longitude=54.3773),
        country_code="ARE",
        operational_status="operational",
        capacity="32.3 million passengers annually",
        critical_infrastructure=True,
        runways=3,
        elevation_meters=7,
        max_capacity_daily=1100,
        airlines=["Etihad Airways", "Air Arabia", "international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-008",
        name="Sharjah International Airport",
        name_ar="مطار الشارقة الدولي",
        icao_code="OMSJ",
        iata_code="SHJ",
        location=GeoPoint(latitude=25.3282, longitude=55.5166),
        country_code="ARE",
        operational_status="operational",
        capacity="9.8 million passengers annually",
        critical_infrastructure=False,
        runways=1,
        elevation_meters=9,
        max_capacity_daily=300,
        airlines=["Air Arabia", "Fly Dubai", "regional operators"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.98,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-009",
        name="Al Fujairah International Airport",
        name_ar="مطار الفجيرة الدولي",
        icao_code="OMFJ",
        iata_code="FJI",
        location=GeoPoint(latitude=25.1166, longitude=56.3400),
        country_code="ARE",
        operational_status="operational",
        capacity="Regional airport",
        critical_infrastructure=False,
        runways=1,
        elevation_meters=5,
        max_capacity_daily=50,
        airlines=["Regional carriers"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.92,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    # Qatar
    airports.append(Airport(
        id="apt-010",
        name="Hamad International Airport",
        name_ar="مطار حمد الدولي",
        icao_code="OTHH",
        iata_code="DOH",
        location=GeoPoint(latitude=25.2731, longitude=51.6139),
        country_code="QAT",
        operational_status="operational",
        capacity="50 million passengers annually",
        critical_infrastructure=True,
        runways=3,
        elevation_meters=2,
        max_capacity_daily=1600,
        airlines=["Qatar Airways", "150+ carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    # Kuwait
    airports.append(Airport(
        id="apt-011",
        name="Kuwait International Airport",
        name_ar="مطار الكويت الدولي",
        icao_code="OKJK",
        iata_code="KWI",
        location=GeoPoint(latitude=29.2262, longitude=47.9688),
        country_code="KWT",
        operational_status="operational",
        capacity="15 million passengers annually",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=76,
        max_capacity_daily=500,
        airlines=["Kuwait Airways", "international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))

    # Bahrain
    airports.append(Airport(
        id="apt-012",
        name="Bahrain International Airport",
        name_ar="مطار البحرين الدولي",
        icao_code="OBBI",
        iata_code="BAH",
        location=GeoPoint(latitude=26.1355, longitude=50.3628),
        country_code="BHR",
        operational_status="operational",
        capacity="9.7 million passengers annually",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=2,
        max_capacity_daily=300,
        airlines=["Gulf Air", "international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))

    # Oman
    airports.append(Airport(
        id="apt-013",
        name="Muscat International Airport",
        name_ar="مطار مسقط الدولي",
        icao_code="OOMS",
        iata_code="MCT",
        location=GeoPoint(latitude=23.5933, longitude=58.2842),
        country_code="OMN",
        operational_status="operational",
        capacity="14.6 million passengers annually",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=2,
        max_capacity_daily=480,
        airlines=["Oman Air", "international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))

    airports.append(Airport(
        id="apt-014",
        name="Salalah Airport",
        name_ar="مطار صلالة",
        icao_code="OOSA",
        iata_code="SLL",
        location=GeoPoint(latitude=17.0391, longitude=54.0910),
        country_code="OMN",
        operational_status="operational",
        capacity="Regional airport",
        critical_infrastructure=False,
        runways=1,
        elevation_meters=80,
        max_capacity_daily=100,
        airlines=["Oman Air", "regional operators"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.95,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))

    # Yemen
    airports.append(Airport(
        id="apt-015",
        name="Sana'a International Airport",
        name_ar="مطار صنعاء الدولي",
        icao_code="OYSI",
        iata_code="SAH",
        location=GeoPoint(latitude=15.5527, longitude=48.5164),
        country_code="YEM",
        operational_status="degraded",
        capacity="Limited operations - conflict affected",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=2159,
        max_capacity_daily=100,
        airlines=["Yemen Airways - limited"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.75,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))

    airports.append(Airport(
        id="apt-016",
        name="Aden Adeni Airport",
        name_ar="مطار عدن عديني",
        icao_code="OYAD",
        iata_code="ADE",
        location=GeoPoint(latitude=12.8289, longitude=45.0165),
        country_code="YEM",
        operational_status="operational",
        capacity="Regional airport - limited capacity",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=7,
        max_capacity_daily=80,
        airlines=["Yemen Airways", "regional operators"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.80,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))

    # Iraq
    airports.append(Airport(
        id="apt-017",
        name="Baghdad International Airport",
        name_ar="مطار بغداد الدولي",
        icao_code="ORBS",
        iata_code="BGW",
        location=GeoPoint(latitude=33.2574, longitude=44.2325),
        country_code="IRQ",
        operational_status="operational",
        capacity="6.8 million passengers annually",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=33,
        max_capacity_daily=230,
        airlines=["Iraqi Airways", "regional carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.92,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-018",
        name="Basra International Airport",
        name_ar="مطار البصرة الدولي",
        icao_code="ORMM",
        iata_code="BSR",
        location=GeoPoint(latitude=30.5356, longitude=47.6586),
        country_code="IRQ",
        operational_status="operational",
        capacity="Limited commercial operations",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=2,
        max_capacity_daily=100,
        airlines=["Iraqi Airways", "regional operators"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.85,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    # Iran
    airports.append(Airport(
        id="apt-019",
        name="Imam Khomeini International Airport",
        name_ar="مطار الإمام الخميني الدولي",
        icao_code="OIKK",
        iata_code="IKA",
        location=GeoPoint(latitude=35.4170, longitude=51.8763),
        country_code="IRN",
        operational_status="operational",
        capacity="17.5 million passengers annually",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=990,
        max_capacity_daily=580,
        airlines=["Iran Air", "regional carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.95,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-020",
        name="Bandar Abbas Shahid Bahonar International Airport",
        name_ar="مطار بندر عباس الدولي",
        icao_code="OICC",
        iata_code="BND",
        location=GeoPoint(latitude=27.0754, longitude=56.3768),
        country_code="IRN",
        operational_status="operational",
        capacity="Regional airport - military focus",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=7,
        max_capacity_daily=150,
        airlines=["Iran Air", "regional operators"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.90,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    # Additional GCC Region Airports
    airports.append(Airport(
        id="apt-021",
        name="King Khalid Military City Airport",
        name_ar="مطار مدينة الملك خالد العسكرية",
        icao_code="OEKC",
        iata_code="KKC",
        location=GeoPoint(latitude=28.3033, longitude=46.0333),
        country_code="SAU",
        operational_status="operational",
        capacity="Military airport",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=413,
        max_capacity_daily=200,
        airlines=["Saudi military operators"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.85,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-022",
        name="Prince Muhammad bin Abdulaziz Airport",
        name_ar="مطار الأمير محمد بن عبدالعزيز",
        icao_code="OEMA",
        iata_code="MED",
        location=GeoPoint(latitude=24.5500, longitude=39.7056),
        country_code="SAU",
        operational_status="operational",
        capacity="Regional airport",
        critical_infrastructure=False,
        runways=1,
        elevation_meters=656,
        max_capacity_daily=150,
        airlines=["Regional carriers"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.90,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-023",
        name="Tabuk Regional Airport",
        name_ar="مطار تبوك الإقليمي",
        icao_code="OETB",
        iata_code="TUC",
        location=GeoPoint(latitude=28.3743, longitude=36.6214),
        country_code="SAU",
        operational_status="operational",
        capacity="Regional airport",
        critical_infrastructure=False,
        runways=1,
        elevation_meters=787,
        max_capacity_daily=100,
        airlines=["Regional carriers"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.88,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-024",
        name="Abqaiq Airport",
        name_ar="مطار العبقيق",
        icao_code="OEAB",
        iata_code="ABQ",
        location=GeoPoint(latitude=25.9167, longitude=49.6333),
        country_code="SAU",
        operational_status="operational",
        capacity="Industrial airport - Saudi Aramco",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=130,
        max_capacity_daily=50,
        airlines=["Aramco operators"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.85,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-025",
        name="Ras Al Khaimah International Airport",
        name_ar="مطار رأس الخيمة الدولي",
        icao_code="OMRK",
        iata_code="RKT",
        location=GeoPoint(latitude=25.6089, longitude=55.9422),
        country_code="ARE",
        operational_status="operational",
        capacity="Regional airport",
        critical_infrastructure=False,
        runways=1,
        elevation_meters=6,
        max_capacity_daily=80,
        airlines=["Regional operators"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.90,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-026",
        name="Al Ain International Airport",
        name_ar="مطار العين الدولي",
        icao_code="OMAA",
        iata_code="AAN",
        location=GeoPoint(latitude=24.2622, longitude=55.6164),
        country_code="ARE",
        operational_status="operational",
        capacity="Regional airport",
        critical_infrastructure=False,
        runways=1,
        elevation_meters=299,
        max_capacity_daily=100,
        airlines=["Regional carriers"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.88,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-027",
        name="Doha International Airport New",
        name_ar="مطار الدوحة الجديد",
        icao_code="OTHH",
        iata_code="DOH",
        location=GeoPoint(latitude=25.2731, longitude=51.6139),
        country_code="QAT",
        operational_status="operational",
        capacity="Hamad International - 50M passengers",
        critical_infrastructure=True,
        runways=3,
        elevation_meters=2,
        max_capacity_daily=1600,
        airlines=["Qatar Airways", "150+ international carriers"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=1.0,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-028",
        name="Masirah Island Airport",
        name_ar="مطار جزيرة مصيرة",
        icao_code="OOMH",
        iata_code="MSH",
        location=GeoPoint(latitude=20.6633, longitude=58.8833),
        country_code="OMN",
        operational_status="operational",
        capacity="Strategic military airport",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=7,
        max_capacity_daily=100,
        airlines=["Military operators"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.85,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-029",
        name="Gwadar International Airport",
        name_ar="مطار غوادر الدولي",
        icao_code="OPGD",
        iata_code="GWD",
        location=GeoPoint(latitude=25.1975, longitude=61.6485),
        country_code="PAK",
        operational_status="operational",
        capacity="Regional gateway airport",
        critical_infrastructure=True,
        runways=1,
        elevation_meters=3,
        max_capacity_daily=200,
        airlines=["Regional operators"],
        international_airport=True,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.88,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    airports.append(Airport(
        id="apt-030",
        name="Kabrit Airbase",
        name_ar="قاعدة كبريت الجوية",
        icao_code="HESK",
        iata_code="KBT",
        location=GeoPoint(latitude=29.9472, longitude=32.2944),
        country_code="EGY",
        operational_status="operational",
        capacity="Military airbase - limited civil",
        critical_infrastructure=True,
        runways=2,
        elevation_meters=193,
        max_capacity_daily=150,
        airlines=["Egyptian military"],
        international_airport=False,
        asset_type=AssetType.AIRPORT,
        source_type=SourceType.INTERNAL_SYSTEM,
        confidence=0.82,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    ))
    
    return airports
