"""Seed data for GCC region flights.

This module provides realistic flight data for the GCC region (2023-2026).
All flights use real aircraft types, airlines, and airports.
"""

from datetime import datetime, timedelta
from typing import Optional

from app.schema import GeoPoint, Flight, FlightStatus


def get_seed_flights() -> list[Flight]:
    """Return a list of GCC region flights with realistic data.
    
    Includes flights connecting major GCC airports with realistic:
    - Aircraft types (Boeing 777, 787, Airbus A380, A350, etc.)
    - Airline operators (Emirates, Saudi, Qatar, Kuwait Airways, Etihad, etc.)
    - Route patterns (intra-GCC, GCC-Europe, GCC-Asia)
    - Flight statuses reflecting real-time operations
    - Current positions along flight paths
    - Realistic delays and diversions for some flights
    
    Returns:
        list[Flight]: 25 realistic GCC region flights
    """
    flights = []
    base_time = datetime.utcnow()
    
    # Emirates flights - Dubai hub
    flights.append(Flight(
        id="flt-001",
        flight_number="EK1",
        operator_id="ops-001",
        operator_name="Emirates Airlines",
        departure_airport_id="OMDB",
        arrival_airport_id="EGLL",
        departure_airport_name="Dubai International",
        arrival_airport_name="London Heathrow",
        scheduled_departure=base_time + timedelta(hours=2),
        scheduled_arrival=base_time + timedelta(hours=9),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 777-300ER",
        aircraft_registration="A6-EWA",
        current_position=GeoPoint(latitude=25.2528, longitude=55.3644),
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=3_360,
        estimated_arrival=base_time + timedelta(hours=9),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.99,
        last_status_update=datetime.utcnow(),
    ))
    
    flights.append(Flight(
        id="flt-002",
        flight_number="EK213",
        operator_id="ops-001",
        operator_name="Emirates Airlines",
        departure_airport_id="OMDB",
        arrival_airport_id="OERK",
        departure_airport_name="Dubai International",
        arrival_airport_name="Riyadh International",
        scheduled_departure=base_time + timedelta(hours=1),
        scheduled_arrival=base_time + timedelta(hours=2.5),
        actual_departure=base_time - timedelta(minutes=5),
        actual_arrival=None,
        status=FlightStatus.ACTIVE,
        aircraft_type="Boeing 737-800",
        aircraft_registration="A6-EMB",
        current_position=GeoPoint(latitude=25.4, longitude=50.5),
        current_altitude_feet=35_000,
        current_speed_knots=480,
        heading=290,
        distance_flown_nm=185,
        distance_remaining_nm=175,
        estimated_arrival=base_time + timedelta(hours=2.3),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.98,
        last_status_update=datetime.utcnow() - timedelta(minutes=2),
    ))
    
    flights.append(Flight(
        id="flt-003",
        flight_number="EK410",
        operator_id="ops-001",
        operator_name="Emirates Airlines",
        departure_airport_id="OERK",
        arrival_airport_id="OMDB",
        departure_airport_name="Riyadh International",
        arrival_airport_name="Dubai International",
        scheduled_departure=base_time + timedelta(hours=3),
        scheduled_arrival=base_time + timedelta(hours=4.5),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Airbus A350-900",
        aircraft_registration="A6-EDB",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=360,
        estimated_arrival=base_time + timedelta(hours=4.5),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.97,
        last_status_update=datetime.utcnow(),
    ))
    
    # Saudi Arabian Airlines flights
    flights.append(Flight(
        id="flt-004",
        flight_number="SV5",
        operator_id="ops-002",
        operator_name="SAUDIA",
        departure_airport_id="OERK",
        arrival_airport_id="EGLL",
        departure_airport_name="Riyadh International",
        arrival_airport_name="London Heathrow",
        scheduled_departure=base_time + timedelta(hours=4),
        scheduled_arrival=base_time + timedelta(hours=11),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 777-300ER",
        aircraft_registration="HZ-AK1",
        current_position=GeoPoint(latitude=24.9266, longitude=46.6989),
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=3_360,
        estimated_arrival=base_time + timedelta(hours=11),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.95,
        last_status_update=datetime.utcnow(),
    ))
    
    flights.append(Flight(
        id="flt-005",
        flight_number="SV102",
        operator_id="ops-002",
        operator_name="SAUDIA",
        departure_airport_id="OEJN",
        arrival_airport_id="OTHH",
        departure_airport_name="Jeddah International",
        arrival_airport_name="Hamad International",
        scheduled_departure=base_time - timedelta(hours=2),
        scheduled_arrival=base_time - timedelta(hours=0.5),
        actual_departure=base_time - timedelta(hours=2, minutes=15),
        actual_arrival=base_time - timedelta(hours=0.5),
        status=FlightStatus.COMPLETED,
        aircraft_type="Airbus A320",
        aircraft_registration="HZ-AS8",
        current_position=GeoPoint(latitude=25.2731, longitude=51.6139),
        current_altitude_feet=0,
        current_speed_knots=0,
        heading=None,
        distance_flown_nm=290,
        distance_remaining_nm=0,
        estimated_arrival=base_time - timedelta(hours=0.5),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.99,
        last_status_update=datetime.utcnow(),
    ))
    
    # Qatar Airways flights
    flights.append(Flight(
        id="flt-006",
        flight_number="QR1",
        operator_id="ops-003",
        operator_name="Qatar Airways",
        departure_airport_id="OTHH",
        arrival_airport_id="EGLL",
        departure_airport_name="Hamad International",
        arrival_airport_name="London Heathrow",
        scheduled_departure=base_time + timedelta(hours=1),
        scheduled_arrival=base_time + timedelta(hours=8),
        actual_departure=base_time + timedelta(minutes=15),
        actual_arrival=None,
        status=FlightStatus.ACTIVE,
        aircraft_type="Boeing 787-8 Dreamliner",
        aircraft_registration="A7-BCA",
        current_position=GeoPoint(latitude=28.0, longitude=35.0),
        current_altitude_feet=40_000,
        current_speed_knots=490,
        heading=320,
        distance_flown_nm=1_200,
        distance_remaining_nm=2_100,
        estimated_arrival=base_time + timedelta(hours=7.9),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.98,
        last_status_update=datetime.utcnow() - timedelta(minutes=3),
    ))
    
    flights.append(Flight(
        id="flt-007",
        flight_number="QR651",
        operator_id="ops-003",
        operator_name="Qatar Airways",
        departure_airport_id="OTHH",
        arrival_airport_id="RJTT",
        departure_airport_name="Hamad International",
        arrival_airport_name="Tokyo Narita",
        scheduled_departure=base_time + timedelta(hours=2),
        scheduled_arrival=base_time + timedelta(hours=18),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Airbus A350-900",
        aircraft_registration="A7-ALA",
        current_position=GeoPoint(latitude=25.2731, longitude=51.6139),
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=4_850,
        estimated_arrival=base_time + timedelta(hours=18),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.96,
        last_status_update=datetime.utcnow(),
    ))
    
    # Etihad Airways flights
    flights.append(Flight(
        id="flt-008",
        flight_number="EY1",
        operator_id="ops-004",
        operator_name="Etihad Airways",
        departure_airport_id="OMAD",
        arrival_airport_id="EGLL",
        departure_airport_name="Abu Dhabi International",
        arrival_airport_name="London Heathrow",
        scheduled_departure=base_time + timedelta(hours=0.5),
        scheduled_arrival=base_time + timedelta(hours=7.5),
        actual_departure=base_time + timedelta(minutes=30),
        actual_arrival=None,
        status=FlightStatus.ACTIVE,
        aircraft_type="Boeing 787-10 Dreamliner",
        aircraft_registration="A6-BMD",
        current_position=GeoPoint(latitude=32.0, longitude=25.0),
        current_altitude_feet=37_000,
        current_speed_knots=475,
        heading=310,
        distance_flown_nm=1_800,
        distance_remaining_nm=1_500,
        estimated_arrival=base_time + timedelta(hours=7.4),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.97,
        last_status_update=datetime.utcnow() - timedelta(minutes=1),
    ))
    
    flights.append(Flight(
        id="flt-009",
        flight_number="EY452",
        operator_id="ops-004",
        operator_name="Etihad Airways",
        departure_airport_id="OMAD",
        arrival_airport_id="OERK",
        departure_airport_name="Abu Dhabi International",
        arrival_airport_name="Riyadh International",
        scheduled_departure=base_time + timedelta(hours=5),
        scheduled_arrival=base_time + timedelta(hours=6),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Airbus A320neo",
        aircraft_registration="A6-ANA",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=240,
        estimated_arrival=base_time + timedelta(hours=6),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.94,
        last_status_update=datetime.utcnow(),
    ))
    
    # Kuwait Airways flights
    flights.append(Flight(
        id="flt-010",
        flight_number="KU101",
        operator_id="ops-005",
        operator_name="Kuwait Airways",
        departure_airport_id="OKJK",
        arrival_airport_id="OMAD",
        departure_airport_name="Kuwait International",
        arrival_airport_name="Abu Dhabi International",
        scheduled_departure=base_time + timedelta(hours=2),
        scheduled_arrival=base_time + timedelta(hours=3.5),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 777-300ER",
        aircraft_registration="9K-AOC",
        current_position=GeoPoint(latitude=29.2262, longitude=47.9688),
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=280,
        estimated_arrival=base_time + timedelta(hours=3.5),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.92,
        last_status_update=datetime.utcnow(),
    ))
    
    flights.append(Flight(
        id="flt-011",
        flight_number="KU501",
        operator_id="ops-005",
        operator_name="Kuwait Airways",
        departure_airport_id="OKJK",
        arrival_airport_id="UUWW",
        departure_airport_name="Kuwait International",
        arrival_airport_name="Moscow Sheremetyevo",
        scheduled_departure=base_time + timedelta(hours=3),
        scheduled_arrival=base_time + timedelta(hours=8),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Airbus A330-200",
        aircraft_registration="9K-APE",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=2_100,
        estimated_arrival=base_time + timedelta(hours=8),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.90,
        last_status_update=datetime.utcnow(),
    ))
    
    # Bahrain Airways flights
    flights.append(Flight(
        id="flt-012",
        flight_number="BG101",
        operator_id="ops-006",
        operator_name="Gulf Air",
        departure_airport_id="OBBI",
        arrival_airport_id="OERK",
        departure_airport_name="Bahrain International",
        arrival_airport_name="Riyadh International",
        scheduled_departure=base_time - timedelta(hours=1),
        scheduled_arrival=base_time - timedelta(minutes=30),
        actual_departure=base_time - timedelta(hours=1, minutes=10),
        actual_arrival=base_time - timedelta(minutes=40),
        status=FlightStatus.COMPLETED,
        aircraft_type="Boeing 737-800",
        aircraft_registration="A9C-BC",
        current_position=GeoPoint(latitude=25.2, longitude=48.0),
        current_altitude_feet=0,
        current_speed_knots=0,
        heading=None,
        distance_flown_nm=240,
        distance_remaining_nm=0,
        estimated_arrival=base_time - timedelta(minutes=30),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.96,
        last_status_update=datetime.utcnow(),
    ))
    
    flights.append(Flight(
        id="flt-013",
        flight_number="BG201",
        operator_id="ops-006",
        operator_name="Gulf Air",
        departure_airport_id="OBBI",
        arrival_airport_id="OTHH",
        departure_airport_name="Bahrain International",
        arrival_airport_name="Hamad International",
        scheduled_departure=base_time + timedelta(hours=6),
        scheduled_arrival=base_time + timedelta(hours=7),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Airbus A320",
        aircraft_registration="A9C-BA",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=100,
        estimated_arrival=base_time + timedelta(hours=7),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.91,
        last_status_update=datetime.utcnow(),
    ))
    
    # Oman Air flights
    flights.append(Flight(
        id="flt-014",
        flight_number="WY502",
        operator_id="ops-007",
        operator_name="Oman Air",
        departure_airport_id="OOMS",
        arrival_airport_id="OMAD",
        departure_airport_name="Muscat International",
        arrival_airport_name="Abu Dhabi International",
        scheduled_departure=base_time + timedelta(hours=2),
        scheduled_arrival=base_time + timedelta(hours=3),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 737-800",
        aircraft_registration="A40-SA",
        current_position=GeoPoint(latitude=23.5933, longitude=58.2842),
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=240,
        estimated_arrival=base_time + timedelta(hours=3),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.89,
        last_status_update=datetime.utcnow(),
    ))
    
    flights.append(Flight(
        id="flt-015",
        flight_number="WY101",
        operator_id="ops-007",
        operator_name="Oman Air",
        departure_airport_id="OOMS",
        arrival_airport_id="EGLL",
        departure_airport_name="Muscat International",
        arrival_airport_name="London Heathrow",
        scheduled_departure=base_time + timedelta(hours=8),
        scheduled_arrival=base_time + timedelta(hours=15),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 787-9 Dreamliner",
        aircraft_registration="A40-MU",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=3_200,
        estimated_arrival=base_time + timedelta(hours=15),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.93,
        last_status_update=datetime.utcnow(),
    ))
    
    # FlyDubai flights
    flights.append(Flight(
        id="flt-016",
        flight_number="FZ3",
        operator_id="ops-008",
        operator_name="flydubai",
        departure_airport_id="OMDB",
        arrival_airport_id="OERS",
        departure_airport_name="Dubai International",
        arrival_airport_name="Sharjah International",
        scheduled_departure=base_time - timedelta(minutes=30),
        scheduled_arrival=base_time,
        actual_departure=base_time - timedelta(minutes=35),
        actual_arrival=base_time + timedelta(minutes=5),
        status=FlightStatus.COMPLETED,
        aircraft_type="Boeing 737-800",
        aircraft_registration="A6-FDB",
        current_position=GeoPoint(latitude=25.3267, longitude=55.4364),
        current_altitude_feet=0,
        current_speed_knots=0,
        heading=None,
        distance_flown_nm=25,
        distance_remaining_nm=0,
        estimated_arrival=base_time,
        delay_minutes=5,
        source_type="ads_b",
        confidence=0.95,
        last_status_update=datetime.utcnow(),
    ))
    
    flights.append(Flight(
        id="flt-017",
        flight_number="FZ10",
        operator_id="ops-008",
        operator_name="flydubai",
        departure_airport_id="OMDB",
        arrival_airport_id="OERK",
        departure_airport_name="Dubai International",
        arrival_airport_name="Riyadh International",
        scheduled_departure=base_time + timedelta(hours=1),
        scheduled_arrival=base_time + timedelta(hours=2.5),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 737-MAX 8",
        aircraft_registration="A6-FMA",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=360,
        estimated_arrival=base_time + timedelta(hours=2.5),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.94,
        last_status_update=datetime.utcnow(),
    ))
    
    # International carrier - Lufthansa
    flights.append(Flight(
        id="flt-018",
        flight_number="LH719",
        operator_id="ops-009",
        operator_name="Lufthansa",
        departure_airport_id="EDDF",
        arrival_airport_id="OMDB",
        departure_airport_name="Frankfurt am Main",
        arrival_airport_name="Dubai International",
        scheduled_departure=base_time - timedelta(hours=4),
        scheduled_arrival=base_time + timedelta(hours=4),
        actual_departure=base_time - timedelta(hours=4, minutes=5),
        actual_arrival=None,
        status=FlightStatus.ACTIVE,
        aircraft_type="Airbus A350-900",
        aircraft_registration="D-AIXA",
        current_position=GeoPoint(latitude=32.0, longitude=45.0),
        current_altitude_feet=41_000,
        current_speed_knots=480,
        heading=135,
        distance_flown_nm=1_800,
        distance_remaining_nm=1_400,
        estimated_arrival=base_time + timedelta(hours=3.9),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.98,
        last_status_update=datetime.utcnow() - timedelta(minutes=5),
    ))
    
    # British Airways
    flights.append(Flight(
        id="flt-019",
        flight_number="BA117",
        operator_id="ops-010",
        operator_name="British Airways",
        departure_airport_id="EGLL",
        arrival_airport_id="OERK",
        departure_airport_name="London Heathrow",
        arrival_airport_name="Riyadh International",
        scheduled_departure=base_time + timedelta(hours=10),
        scheduled_arrival=base_time + timedelta(hours=18),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 787-9 Dreamliner",
        aircraft_registration="G-ZBKP",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=3_360,
        estimated_arrival=base_time + timedelta(hours=18),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.96,
        last_status_update=datetime.utcnow(),
    ))
    
    # Turkish Airlines
    flights.append(Flight(
        id="flt-020",
        flight_number="TK901",
        operator_id="ops-011",
        operator_name="Turkish Airlines",
        departure_airport_id="LTAC",
        arrival_airport_id="OMDB",
        departure_airport_name="Istanbul Atatürk",
        arrival_airport_name="Dubai International",
        scheduled_departure=base_time + timedelta(hours=7),
        scheduled_arrival=base_time + timedelta(hours=13),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Airbus A350-900",
        aircraft_registration="TC-LOB",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=2_100,
        estimated_arrival=base_time + timedelta(hours=13),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.92,
        last_status_update=datetime.utcnow(),
    ))
    
    # Air India
    flights.append(Flight(
        id="flt-021",
        flight_number="AI901",
        operator_id="ops-012",
        operator_name="Air India",
        departure_airport_id="VIDP",
        arrival_airport_id="OMDB",
        departure_airport_name="Delhi Indira Gandhi",
        arrival_airport_name="Dubai International",
        scheduled_departure=base_time + timedelta(hours=6),
        scheduled_arrival=base_time + timedelta(hours=9),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 787-8 Dreamliner",
        aircraft_registration="VT-ANP",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=1_450,
        estimated_arrival=base_time + timedelta(hours=9),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.90,
        last_status_update=datetime.utcnow(),
    ))
    
    # China Eastern Airlines
    flights.append(Flight(
        id="flt-022",
        flight_number="MU772",
        operator_id="ops-013",
        operator_name="China Eastern Airlines",
        departure_airport_id="ZSSS",
        arrival_airport_id="OMDB",
        departure_airport_name="Shanghai Pudong",
        arrival_airport_name="Dubai International",
        scheduled_departure=base_time + timedelta(hours=9),
        scheduled_arrival=base_time + timedelta(hours=18),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 777-300ER",
        aircraft_registration="B-2010",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=3_200,
        estimated_arrival=base_time + timedelta(hours=18),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.88,
        last_status_update=datetime.utcnow(),
    ))
    
    # Japan Airlines
    flights.append(Flight(
        id="flt-023",
        flight_number="JL777",
        operator_id="ops-014",
        operator_name="Japan Airlines",
        departure_airport_id="RJTT",
        arrival_airport_id="OMDB",
        departure_airport_name="Tokyo Narita",
        arrival_airport_name="Dubai International",
        scheduled_departure=base_time + timedelta(hours=11),
        scheduled_arrival=base_time + timedelta(hours=20),
        actual_departure=None,
        actual_arrival=None,
        status=FlightStatus.SCHEDULED,
        aircraft_type="Boeing 787-9 Dreamliner",
        aircraft_registration="JA874J",
        current_position=None,
        current_altitude_feet=None,
        current_speed_knots=None,
        heading=None,
        distance_flown_nm=None,
        distance_remaining_nm=3_650,
        estimated_arrival=base_time + timedelta(hours=20),
        delay_minutes=0,
        source_type="ads_b",
        confidence=0.91,
        last_status_update=datetime.utcnow(),
    ))
    
    # Delayed flight example
    flights.append(Flight(
        id="flt-024",
        flight_number="EK215",
        operator_id="ops-001",
        operator_name="Emirates Airlines",
        departure_airport_id="OMDB",
        arrival_airport_id="OERK",
        departure_airport_name="Dubai International",
        arrival_airport_name="Riyadh International",
        scheduled_departure=base_time - timedelta(hours=1),
        scheduled_arrival=base_time + timedelta(minutes=30),
        actual_departure=base_time - timedelta(minutes=50),
        actual_arrival=None,
        status=FlightStatus.DELAYED,
        aircraft_type="Boeing 737-800",
        aircraft_registration="A6-EMC",
        current_position=GeoPoint(latitude=25.1, longitude=49.0),
        current_altitude_feet=32_000,
        current_speed_knots=460,
        heading=295,
        distance_flown_nm=150,
        distance_remaining_nm=210,
        estimated_arrival=base_time + timedelta(hours=1),
        delay_minutes=25,
        source_type="ads_b",
        confidence=0.97,
        last_status_update=datetime.utcnow() - timedelta(minutes=4),
    ))
    
    # Diverted flight example
    flights.append(Flight(
        id="flt-025",
        flight_number="EY104",
        operator_id="ops-004",
        operator_name="Etihad Airways",
        departure_airport_id="OERK",
        arrival_airport_id="OMDB",
        departure_airport_name="Riyadh International",
        arrival_airport_name="Dubai International",
        scheduled_departure=base_time - timedelta(hours=2),
        scheduled_arrival=base_time - timedelta(hours=0.5),
        actual_departure=base_time - timedelta(hours=2, minutes=5),
        actual_arrival=base_time - timedelta(minutes=10),
        status=FlightStatus.DIVERTED,
        aircraft_type="Airbus A320",
        aircraft_registration="A6-AEB",
        current_position=GeoPoint(latitude=25.3267, longitude=55.4364),
        current_altitude_feet=0,
        current_speed_knots=0,
        heading=None,
        distance_flown_nm=360,
        distance_remaining_nm=0,
        estimated_arrival=base_time - timedelta(hours=0.5),
        delay_minutes=20,
        diversion_airport_id="OERS",
        source_type="ads_b",
        confidence=0.99,
        last_status_update=datetime.utcnow(),
    ))
    
    return flights
