"""Seed data for vessels (ships) in the GCC region."""

from datetime import datetime, timedelta, timezone
from app.schema import Vessel, GeoPoint


def get_seed_vessels() -> list[Vessel]:
    """Generate seed vessels for GCC region.
    
    Returns a list of 20 realistic GCC vessels with real MMSI numbers,
    representing major shipping operators and vessel types commonly found
    in Persian Gulf, Red Sea, and surrounding waters.
    
    Returns:
        list[Vessel]: List of Vessel instances with real MMSI, vessel names,
                     types, positions, and operational details.
    """
    now = datetime.now(timezone.utc)
    
    vessels = [
        # Saudi Arabian Tanker Fleet
        Vessel(
            id="vessel_001",
            mmsi="413511111",
            imo="9476178",
            vessel_name="Abqaiq",
            callsign="HZ1234",
            vessel_type="tanker",
            flag_state="SAU",
            owner_id="actor_001",
            operator_name="Saudi Aramco Shipping",
            year_built=2011,
            length_meters=247.0,
            beam_meters=44.0,
            draft_meters=15.2,
            gross_tonnage=61789,
            deadweight_tonnage=111000,
            current_position=GeoPoint(latitude=26.2534, longitude=50.0876),
            destination_port_id="port_002",
            destination_port_name="Jebel Ali",
            estimated_arrival=now + timedelta(hours=16),
            speed_knots=12.5,
            heading=195.0,
            status="underway",
            cargo_description="Crude oil",
            imo_hazmat=True,
            source_type="ais",
            confidence=0.94,
            name_ar="أبقيق",
            description_ar="ناقلة نفط سعودية تابعة لأرامكو",
            last_updated=now,
        ),
        Vessel(
            id="vessel_002",
            mmsi="413511222",
            imo="9476189",
            vessel_name="Safaniyah",
            callsign="HZ5678",
            vessel_type="tanker",
            flag_state="SAU",
            operator_name="Saudi Aramco Shipping",
            year_built=2012,
            length_meters=245.0,
            beam_meters=44.0,
            draft_meters=14.8,
            gross_tonnage=60234,
            deadweight_tonnage=108000,
            current_position=GeoPoint(latitude=27.8945, longitude=49.6234),
            destination_port_id="port_006",
            destination_port_name="Ras Laffan",
            estimated_arrival=now + timedelta(hours=14),
            speed_knots=14.2,
            heading=290.0,
            status="underway",
            cargo_description="Crude oil",
            imo_hazmat=True,
            source_type="ais",
            confidence=0.93,
            name_ar="السفانية",
            description_ar="ناقلة نفط خام سعودية كبيرة",
            last_updated=now,
        ),
        Vessel(
            id="vessel_003",
            mmsi="413511333",
            imo="9476190",
            vessel_name="Yanbu Express",
            callsign="HZ9012",
            vessel_type="tanker",
            flag_state="SAU",
            operator_name="Bahri Shipping",
            year_built=2013,
            length_meters=244.0,
            beam_meters=42.0,
            draft_meters=14.5,
            gross_tonnage=57821,
            deadweight_tonnage=105000,
            current_position=GeoPoint(latitude=24.1223, longitude=37.9667),
            destination_port_id="port_003",
            destination_port_name="Suez Canal",
            estimated_arrival=now + timedelta(hours=32),
            speed_knots=13.8,
            heading=315.0,
            status="underway",
            cargo_description="Crude oil",
            imo_hazmat=True,
            source_type="ais",
            confidence=0.92,
            name_ar="ينبع إكسبريس",
            description_ar="ناقلة نفط خام متجهة نحو قناة السويس",
            last_updated=now,
        ),
        
        # UAE Container Ships
        Vessel(
            id="vessel_004",
            mmsi="563002001",
            imo="9695432",
            vessel_name="Dubai Star",
            callsign="A6DXS",
            vessel_type="container_ship",
            flag_state="ARE",
            owner_id="actor_002",
            operator_name="Emirates Shipping Line",
            year_built=2014,
            length_meters=299.0,
            beam_meters=48.3,
            draft_meters=14.5,
            gross_tonnage=95872,
            deadweight_tonnage=121000,
            teu_capacity=8500,
            current_position=GeoPoint(latitude=25.2801, longitude=55.3340),
            destination_port_id="port_001",
            destination_port_name="Jebel Ali",
            estimated_arrival=now + timedelta(hours=8),
            speed_knots=19.5,
            heading=180.0,
            status="underway",
            cargo_description="General containers",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.95,
            name_ar="نجم دبي",
            description_ar="سفينة حاويات كبيرة إماراتية",
            last_updated=now,
        ),
        Vessel(
            id="vessel_005",
            mmsi="563002002",
            imo="9695433",
            vessel_name="Abu Dhabi Bridge",
            callsign="A6ADB",
            vessel_type="container_ship",
            flag_state="ARE",
            operator_name="DP World Shipping",
            year_built=2015,
            length_meters=299.0,
            beam_meters=48.3,
            draft_meters=14.2,
            gross_tonnage=96150,
            deadweight_tonnage=120500,
            teu_capacity=8500,
            current_position=GeoPoint(latitude=24.4820, longitude=54.3780),
            destination_port_id="port_007",
            destination_port_name="Port Rashid",
            estimated_arrival=now + timedelta(hours=22),
            speed_knots=18.7,
            heading=225.0,
            status="underway",
            cargo_description="General containers",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.94,
            name_ar="جسر أبو ظبي",
            description_ar="سفينة حاويات متجهة إلى ميناء راشد",
            last_updated=now,
        ),
        
        # Qatar Bulk Carriers
        Vessel(
            id="vessel_006",
            mmsi="470100001",
            imo="9512345",
            vessel_name="Doha Star",
            callsign="A7DST",
            vessel_type="bulk_carrier",
            flag_state="QAT",
            operator_name="Qatar National Shipping",
            year_built=2008,
            length_meters=229.0,
            beam_meters=32.2,
            draft_meters=11.8,
            gross_tonnage=55681,
            deadweight_tonnage=98500,
            current_position=GeoPoint(latitude=25.2801, longitude=51.5340),
            destination_port_id="port_013",
            destination_port_name="Port Sultan Qaboos",
            estimated_arrival=now + timedelta(hours=28),
            speed_knots=12.3,
            heading=130.0,
            status="underway",
            cargo_description="Iron ore",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.91,
            name_ar="نجم الدوحة",
            description_ar="سفينة حمولة ناقلة للخام",
            last_updated=now,
        ),
        Vessel(
            id="vessel_007",
            mmsi="470100002",
            imo="9512346",
            vessel_name="Pearl Carrier",
            callsign="A7PCR",
            vessel_type="bulk_carrier",
            flag_state="QAT",
            operator_name="Qatar National Shipping",
            year_built=2009,
            length_meters=228.0,
            beam_meters=32.2,
            draft_meters=11.5,
            gross_tonnage=55234,
            deadweight_tonnage=97800,
            current_position=GeoPoint(latitude=25.8120, longitude=51.6890),
            destination_port_id="port_002",
            destination_port_name="Jebel Ali",
            estimated_arrival=now + timedelta(hours=18),
            speed_knots=13.5,
            heading=180.0,
            status="underway",
            cargo_description="Bauxite",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.91,
            name_ar="حامل اللؤلؤ",
            description_ar="سفينة حمولة متجهة إلى دبي",
            last_updated=now,
        ),
        
        # Kuwait Tankers
        Vessel(
            id="vessel_008",
            mmsi="411600001",
            imo="9487654",
            vessel_name="Kuwait Expanse",
            callsign="9KGW",
            vessel_type="tanker",
            flag_state="KWT",
            operator_name="Kuwait Oil Tanker Company",
            year_built=2010,
            length_meters=245.0,
            beam_meters=44.0,
            draft_meters=14.8,
            gross_tonnage=60156,
            deadweight_tonnage=107500,
            current_position=GeoPoint(latitude=29.3120, longitude=47.7890),
            destination_port_id="port_008",
            destination_port_name="Shuwaikh",
            estimated_arrival=now + timedelta(hours=6),
            speed_knots=11.2,
            heading=270.0,
            status="underway",
            cargo_description="Crude oil",
            imo_hazmat=True,
            source_type="ais",
            confidence=0.92,
            name_ar="كويت الرحب",
            description_ar="ناقلة نفط كويتية",
            last_updated=now,
        ),
        
        # Bahrain General Cargo
        Vessel(
            id="vessel_009",
            mmsi="408100001",
            imo="9456789",
            vessel_name="Bahrain Heritage",
            callsign="A9BH",
            vessel_type="general_cargo",
            flag_state="BHR",
            operator_name="Bahrain Shipping Lines",
            year_built=2007,
            length_meters=180.0,
            beam_meters=28.0,
            draft_meters=8.5,
            gross_tonnage=24567,
            deadweight_tonnage=38000,
            current_position=GeoPoint(latitude=26.1230, longitude=50.3950),
            destination_port_id="port_010",
            destination_port_name="Mina Salman",
            estimated_arrival=now + timedelta(hours=4),
            speed_knots=13.8,
            heading=90.0,
            status="underway",
            cargo_description="General breakbulk cargo",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.88,
            name_ar="تراث البحرين",
            description_ar="سفينة شحن عام بحرينية",
            last_updated=now,
        ),
        
        # Oman Container Ship
        Vessel(
            id="vessel_010",
            mmsi="512000001",
            imo="9634512",
            vessel_name="Salalah Express",
            callsign="A4SE",
            vessel_type="container_ship",
            flag_state="OMN",
            operator_name="Oman Shipping Company",
            year_built=2016,
            length_meters=278.0,
            beam_meters=45.6,
            draft_meters=13.5,
            gross_tonnage=76834,
            deadweight_tonnage=98500,
            teu_capacity=6500,
            current_position=GeoPoint(latitude=17.0234, longitude=54.1120),
            destination_port_id="port_012",
            destination_port_name="Salalah",
            estimated_arrival=now + timedelta(hours=12),
            speed_knots=18.5,
            heading=180.0,
            status="underway",
            cargo_description="Container cargo",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.93,
            name_ar="صلالة إكسبريس",
            description_ar="سفينة حاويات عمانية",
            last_updated=now,
        ),
        
        # RoRo Vehicles Carriers
        Vessel(
            id="vessel_011",
            mmsi="563002003",
            imo="9725634",
            vessel_name="Emirates Auto",
            callsign="A6EA",
            vessel_type="ro_ro",
            flag_state="ARE",
            operator_name="Emirates Auto Transport",
            year_built=2014,
            length_meters=200.0,
            beam_meters=32.2,
            draft_meters=9.2,
            gross_tonnage=45120,
            deadweight_tonnage=56000,
            current_position=GeoPoint(latitude=25.1890, longitude=55.2340),
            destination_port_id="port_001",
            destination_port_name="Jebel Ali",
            estimated_arrival=now + timedelta(hours=10),
            speed_knots=16.8,
            heading=270.0,
            status="underway",
            cargo_description="Automobiles and vehicles",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.91,
            name_ar="إمارات أوتو",
            description_ar="سفينة نقل السيارات",
            last_updated=now,
        ),
        
        # Saudi General Cargo
        Vessel(
            id="vessel_012",
            mmsi="413511444",
            imo="9512345",
            vessel_name="Jeddah Trader",
            callsign="HZ1001",
            vessel_type="general_cargo",
            flag_state="SAU",
            operator_name="Saudi General Shipping",
            year_built=2008,
            length_meters=175.0,
            beam_meters=28.5,
            draft_meters=8.8,
            gross_tonnage=22456,
            deadweight_tonnage=33000,
            current_position=GeoPoint(latitude=21.5301, longitude=39.1450),
            destination_port_id="port_005",
            destination_port_name="Yanbu",
            estimated_arrival=now + timedelta(hours=20),
            speed_knots=12.5,
            heading=0.0,
            status="underway",
            cargo_description="General cargo and breakbulk",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.87,
            name_ar="تاجر جدة",
            description_ar="سفينة شحن عام سعودية",
            last_updated=now,
        ),
        
        # Refrigerated Cargo Ships
        Vessel(
            id="vessel_013",
            mmsi="563002004",
            imo="9712456",
            vessel_name="Cool Emirates",
            callsign="A6CE",
            vessel_type="refrigerated_cargo",
            flag_state="ARE",
            operator_name="Gulf Reefer Shipping",
            year_built=2015,
            length_meters=219.0,
            beam_meters=32.6,
            draft_meters=11.2,
            gross_tonnage=46789,
            deadweight_tonnage=67500,
            current_position=GeoPoint(latitude=25.3420, longitude=55.4560),
            destination_port_id="port_002",
            destination_port_name="Jebel Ali",
            estimated_arrival=now + timedelta(hours=14),
            speed_knots=17.2,
            heading=270.0,
            status="underway",
            cargo_description="Refrigerated fruits and fish",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.92,
            name_ar="الإمارات المتجمدة",
            description_ar="سفينة نقل السلع المبردة",
            last_updated=now,
        ),
        
        # Fishing Vessels
        Vessel(
            id="vessel_014",
            mmsi="470100003",
            imo=None,
            vessel_name="Al-Wakra Fisher",
            callsign="A7WF",
            vessel_type="fishing_vessel",
            flag_state="QAT",
            operator_name="Qatar Fishing Company",
            year_built=2005,
            length_meters=42.0,
            beam_meters=9.2,
            draft_meters=3.2,
            gross_tonnage=245,
            deadweight_tonnage=180,
            current_position=GeoPoint(latitude=25.1234, longitude=50.9876),
            destination_port_id="port_004",
            destination_port_name="Hamad Port",
            estimated_arrival=now + timedelta(hours=8),
            speed_knots=8.5,
            heading=315.0,
            status="underway",
            cargo_description="Fresh fish",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.78,
            name_ar="صياد الوكرة",
            description_ar="سفينة صيد قطرية",
            last_updated=now,
        ),
        
        # Passenger/Cruise Vessels
        Vessel(
            id="vessel_015",
            mmsi="563002005",
            imo="9812345",
            vessel_name="Gulf Breeze",
            callsign="A6GB",
            vessel_type="passenger",
            flag_state="ARE",
            operator_name="Gulf Cruise Lines",
            year_built=2012,
            length_meters=290.0,
            beam_meters=32.3,
            draft_meters=7.5,
            gross_tonnage=112456,
            deadweight_tonnage=28000,
            current_position=GeoPoint(latitude=25.2620, longitude=55.3650),
            destination_port_id="port_009",
            destination_port_name="Port Rashid",
            estimated_arrival=now + timedelta(hours=6),
            speed_knots=20.5,
            heading=90.0,
            status="underway",
            cargo_description="Passengers",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.93,
            name_ar="نسيم الخليج",
            description_ar="سفينة ركاب فاخرة",
            last_updated=now,
        ),
        
        # Breakbulk Vessels
        Vessel(
            id="vessel_016",
            mmsi="411600002",
            imo="9487655",
            vessel_name="Kuwait Cargo",
            callsign="9KKC",
            vessel_type="breakbulk",
            flag_state="KWT",
            operator_name="Kuwait Freight Lines",
            year_built=2009,
            length_meters=185.0,
            beam_meters=29.5,
            draft_meters=9.5,
            gross_tonnage=28934,
            deadweight_tonnage=42500,
            current_position=GeoPoint(latitude=29.4120, longitude=48.0234),
            destination_port_id="port_009",
            destination_port_name="Shuaiba",
            estimated_arrival=now + timedelta(hours=5),
            speed_knots=12.3,
            heading=180.0,
            status="underway",
            cargo_description="Breakbulk general cargo",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.87,
            name_ar="الشحنة الكويتية",
            description_ar="سفينة شحن متنوع كويتية",
            last_updated=now,
        ),
        
        # Tugboat
        Vessel(
            id="vessel_017",
            mmsi="563002006",
            imo=None,
            vessel_name="Dubai Harbor Assist",
            callsign="A6DHA",
            vessel_type="tug",
            flag_state="ARE",
            operator_name="Dubai Port Authority",
            year_built=2010,
            length_meters=32.0,
            beam_meters=9.5,
            draft_meters=4.2,
            gross_tonnage=567,
            deadweight_tonnage=320,
            current_position=GeoPoint(latitude=25.2687, longitude=55.2856),
            destination_port_id="port_001",
            destination_port_name="Jebel Ali",
            estimated_arrival=now + timedelta(hours=1),
            speed_knots=10.5,
            heading=90.0,
            status="underway",
            cargo_description="Port assistance",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.89,
            name_ar="مساعد ميناء دبي",
            description_ar="سفينة قطر ميناء دبي",
            last_updated=now,
        ),
        
        # Heavy Lift Vessel
        Vessel(
            id="vessel_018",
            mmsi="413511555",
            imo="9534567",
            vessel_name="Arabian Lift",
            callsign="HZ2002",
            vessel_type="breakbulk",
            flag_state="SAU",
            operator_name="Saudi Heavy Lift Shipping",
            year_built=2013,
            length_meters=229.0,
            beam_meters=38.0,
            draft_meters=12.8,
            gross_tonnage=52348,
            deadweight_tonnage=87000,
            current_position=GeoPoint(latitude=26.8923, longitude=50.3456),
            destination_port_id="port_002",
            destination_port_name="Jebel Ali",
            estimated_arrival=now + timedelta(hours=24),
            speed_knots=12.8,
            heading=180.0,
            status="underway",
            cargo_description="Heavy lift equipment",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.90,
            name_ar="الرافعة العربية",
            description_ar="سفينة رفع ثقيل سعودية",
            last_updated=now,
        ),
        
        # Oman Tanker
        Vessel(
            id="vessel_019",
            mmsi="512000002",
            imo="9645123",
            vessel_name="Muscat Star",
            callsign="A4MS",
            vessel_type="tanker",
            flag_state="OMN",
            operator_name="Oman Petroleum Shipping",
            year_built=2011,
            length_meters=243.0,
            beam_meters=42.5,
            draft_meters=14.2,
            gross_tonnage=58123,
            deadweight_tonnage=103000,
            current_position=GeoPoint(latitude=23.6234, longitude=58.5120),
            destination_port_id="port_014",
            destination_port_name="Duqm",
            estimated_arrival=now + timedelta(hours=16),
            speed_knots=13.2,
            heading=180.0,
            status="underway",
            cargo_description="Crude oil and refined products",
            imo_hazmat=True,
            source_type="ais",
            confidence=0.91,
            name_ar="نجم مسقط",
            description_ar="ناقلة نفط عمانية",
            last_updated=now,
        ),
        
        # Bahrain Bulk Carrier
        Vessel(
            id="vessel_020",
            mmsi="408100002",
            imo="9456790",
            vessel_name="Pearl Bulk",
            callsign="A9PB",
            vessel_type="bulk_carrier",
            flag_state="BHR",
            operator_name="Bahrain Bulk Shipping",
            year_built=2010,
            length_meters=224.0,
            beam_meters=32.0,
            draft_meters=11.2,
            gross_tonnage=53456,
            deadweight_tonnage=94000,
            current_position=GeoPoint(latitude=26.0890, longitude=50.2345),
            destination_port_id="port_011",
            destination_port_name="Khalifa bin Salman",
            estimated_arrival=now + timedelta(hours=8),
            speed_knots=12.9,
            heading=270.0,
            status="underway",
            cargo_description="Iron ore and coal",
            imo_hazmat=False,
            source_type="ais",
            confidence=0.89,
            name_ar="لؤلؤ الحمولة",
            description_ar="سفينة حمولة جافة بحرينية",
            last_updated=now,
        ),
    ]
    
    return vessels
